import assert from 'node:assert/strict';
import { Jf, Wf, _, np, op } from '../src/editorialEvaluationHelpers.js';

const settings = {
  mode: 'novel',
  genre: 'ミステリー',
  theme: '秘密',
  era: '現代',
  worldview: '商店街',
  narration: '三人称',
  target: '大人向け',
  ending: '余韻',
};

const methodStack = Jf(settings, 'standard');
assert.match(methodStack, /narrative method stack/);
assert.match(methodStack, /Setup-Payoff/);
assert.match(methodStack, /genre=ミステリー/);
assert.match(methodStack, /worldview=商店街/);

const contract = _(settings, 'standard');
assert.match(contract, /Gen-4 quality contract/);
assert.match(contract, /human noise/);
assert.match(contract, /narrative method stack/);

const evalPrompt = Wf('これは評価対象の本文です。'.repeat(20), settings);
assert.match(evalPrompt, /professional fiction editor/);
assert.match(evalPrompt, /visible generated prose/);
assert.match(evalPrompt, /fact_logic/);
assert.match(evalPrompt, /de_biasing/);
assert.doesNotMatch(evalPrompt, /Generated By AI Story Maker/i);

const parsed = np(`prefix {
  "scores": {
    "fact_logic": 150,
    "emotional_arc": -5,
    "human_noise": 80.4,
    "constraint_fit": 91,
    "prose_commercial": 88,
    "narrative_methods": 77,
    "category_guides": 66,
    "de_biasing": 55
  },
  "strongest_point": "人物の迷い",
  "weakest_point": "終盤が薄い",
  "findings": ["a", "b", "c", "d", "e", "f"],
  "revision_hint": "会話を増やす",
  "pass": false
} suffix`);
assert.equal(parsed.scores.fact_logic, 100);
assert.equal(parsed.scores.emotional_arc, 0);
assert.equal(parsed.scores.human_noise, 80);
assert.equal(parsed.findings.length, 5);
assert.equal(parsed.pass, false);

const formatted = op(parsed);
assert.match(formatted, /Gen-4 AI Evaluation/);
assert.match(formatted, /Fact\/Logic/);
assert.match(formatted, /人物の迷い/);
assert.match(formatted, /会話を増やす/);
assert.match(formatted, /a \/ b \/ c \/ d \/ e/);

console.log('editorialEvaluationHelpers tests passed');
