import assert from 'node:assert/strict';
import { STORY_MAKER_FOOTER } from '../src/version.js';
import { Lr, jt, zf } from '../src/footerHelpers.js';

assert.equal(zf(), STORY_MAKER_FOOTER);
assert.equal(jt(`本文\n\n${STORY_MAKER_FOOTER}`), '本文');
assert.equal(jt('本文\nGenerated by Super FURU AI Story v4.9.0'), '本文');
assert.equal(jt('本文\nCreated By AI Story Maker V5.0.2.'), '本文');
assert.equal(Lr('本文'), `本文\n\n${STORY_MAKER_FOOTER}`);
assert.equal(Lr(`本文\n\n${STORY_MAKER_FOOTER}`), `本文\n\n${STORY_MAKER_FOOTER}`);
assert.equal(Lr(''), STORY_MAKER_FOOTER);

console.log('footerHelpers tests passed');
