import assert from 'node:assert/strict';

import {
  buildLetterFallbackText,
  cleanLetterOutput,
  extractLetterCandidateLines,
  getLetterRepairContext,
  isLetterOutputInvalid,
  repairLetterOutputText,
} from '../src/letterOutputRepair.js';

assert.equal(isLetterOutputInvalid('短い本文', 'novel'), false);
assert.equal(isLetterOutputInvalid('短い本文', 'letter'), true);

const completeLetter = [
  '宛先: 大切なあなたへ',
  '本文:',
  '今日は駅前での出来事を思い出しながら、この手紙を書いています。'.repeat(8),
  '結び:',
  'また話せる日を待っています。',
  '差出人: 物語メーカー',
].join('\n');
assert.equal(isLetterOutputInvalid(completeLetter, 'letter'), false);

assert.equal(
  cleanLetterOutput('【タイトル】\r\n宛先: 友人へ\r\n\r\n\r\n本文: ありがとう\r\n【完】', 'letter'),
  '宛先: 友人へ\n\n本文: ありがとう',
);
assert.equal(cleanLetterOutput('【タイトル】\n本文', 'novel'), '【タイトル】\n本文');

const extracted = extractLetterCandidateLines([
  'Generated By AI Story Maker V5.2.1',
  '【宛先: 母へ】',
  'Prompt: write a letter',
  '駅前の雨で少しだけ立ち止まりました。',
  'Scenario: ignored',
].join('\n'));
assert.deepEqual(extracted, ['宛先: 母へ', '駅前の雨で少しだけ立ち止まりました。']);

const context = getLetterRepairContext({
  themeCustom: '雨の日の買い物',
  genre: '家族',
  worldviewCustom: '駅前の商店街',
  endingCustom: 'バッド寄りの余韻',
});
assert.deepEqual(context, {
  theme: '雨の日の買い物',
  genre: '家族',
  worldview: '駅前の商店街',
  ending: 'バッド寄りの余韻',
});

const fallback = buildLetterFallbackText('宛先: 母へ\n短い断片', context);
assert.match(fallback, /^宛先: 母へ/);
assert.match(fallback, /本文:/);
assert.match(fallback, /駅前の商店街で起きた雨の日の買い物/);
assert.match(fallback, /返事は急ぎません/);
assert.match(fallback, /差出人: 物語メーカー/);

const repaired = repairLetterOutputText('宛先: 友人へ', { theme: '約束', genre: '日常' });
assert.match(repaired, /宛先: 友人へ/);
assert.match(repaired, /本文:/);
assert.match(repaired, /差出人: 物語メーカー/);

console.log('letterOutputRepair tests passed');
