import { Ce } from './domHelpers.js';
import { buildStoryExportFileName } from './fileIoHelpers.js';

const MAX_TITLE_CHARS = 70;
const MAX_INTRODUCTION_CHARS = 1200;
const MAX_TAGS = 10;
const MAX_TAG_CHARS = 20;
const STORY_FOOTER_PATTERN = /\n?\s*(?:Created By AI Story Maker V[\d.]+|Generated By AI Story Maker V[\d.]+|Generated by Super FURU AI Story v[\d.]+)\s*$/i;
const TITLE_LABEL_PATTERN = /(?:^|\n)\s*(?:小説タイトル|タイトル|題名|作品名)\s*[:：]\s*([^\n]{1,100})/u;
const TITLE_LABEL_LINE_PATTERN = /^\s*(?:小説タイトル|タイトル|題名|作品名)\s*[:：]\s*([^\n]{1,100})\s*$/u;
const CHAPTER_HEADING_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?(?:(?:第[0-9０-９一二三四五六七八九十百千]+[章話節](?:[\t \u3000:：\-ー―・]+[^\n【】]{0,60})?)|(?:プロローグ|エピローグ|序章|終章)(?:[\t \u3000:：\-ー―・]+[^\n【】]{0,60})?)(?:[\t \u3000]*】)?[\t \u3000]*$/u;
const CHAPTER_HEADING_PREFIX_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?(?:(?:第[0-9０-９一二三四五六七八九十百千]+[章話節](?:[\t \u3000:：\-ー―・]+[^\n【】\s\u3000]{1,32})?)|(?:プロローグ|エピローグ|序章|終章)(?:[\t \u3000:：\-ー―・]+[^\n【】\s\u3000]{1,32})?)(?:[\t \u3000]*】)?[\t \u3000]+/u;
const STANDALONE_FINISH_PATTERN = /^[\t \u3000]*(?:【\s*)?完(?:\s*】)?[\t \u3000]*$/u;

function normalizeText(value) {
  return String(value || '').replace(/\r\n?/g, '\n').trim();
}

function compactSpaces(value) {
  return String(value || '').replace(/\s+/g, ' ').trim();
}

function charLength(value) {
  return Array.from(String(value || '')).length;
}

function limitChars(value, max, suffix = '') {
  const chars = Array.from(String(value || '').trim());
  if (chars.length <= max) return chars.join('');
  const suffixChars = Array.from(suffix);
  const keep = Math.max(0, max - suffixChars.length);
  return `${chars.slice(0, keep).join('')}${suffix}`;
}

function stripStoryMakerFooter(text) {
  let current = normalizeText(text);
  for (let index = 0; index < 3; index += 1) {
    current = current.replace(STORY_FOOTER_PATTERN, '').trim();
  }
  return current;
}

function cleanTitleCandidate(value) {
  return compactSpaces(value)
    .replace(/^#+/, '')
    .replace(/^[「『【《〈"']+|[」』】》〉"']+$/g, '')
    .replace(/[。！？!?]+$/g, '')
    .trim();
}

function cleanHeadingLabel(value) {
  return compactSpaces(value)
    .replace(/^[#\s\u3000【]+|[】\s\u3000]+$/gu, '')
    .trim();
}

function isChapterHeadingLine(value) {
  return CHAPTER_HEADING_PATTERN.test(String(value || '').trim());
}

function isLikelyTitleLine(value) {
  const title = cleanTitleCandidate(value);
  return (
    title
    && charLength(title) <= MAX_TITLE_CHARS
    && !/[。！？!?]$/.test(value)
    && !isChapterHeadingLine(title)
    && !STANDALONE_FINISH_PATTERN.test(title)
    && !/^Created By|^Generated By/i.test(title)
  );
}

function extractTitle(text, settings = {}) {
  const body = stripStoryMakerFooter(text);
  const labeled = body.match(TITLE_LABEL_PATTERN);
  if (labeled) return limitChars(cleanTitleCandidate(labeled[1]), MAX_TITLE_CHARS);

  const lines = body.split('\n').map(line => line.trim()).filter(Boolean);
  const bracketed = lines[0]?.match(/^【(.{1,70})】$/u);
  if (bracketed && !isChapterHeadingLine(bracketed[1])) {
    return limitChars(cleanTitleCandidate(bracketed[1]), MAX_TITLE_CHARS);
  }
  const markdown = lines[0]?.match(/^[#＃]+\s*(.{1,70})$/u);
  if (markdown && !isChapterHeadingLine(markdown[1])) {
    return limitChars(cleanTitleCandidate(markdown[1]), MAX_TITLE_CHARS);
  }
  if (lines[0] && isLikelyTitleLine(lines[0])) {
    return limitChars(cleanTitleCandidate(lines[0]), MAX_TITLE_CHARS);
  }

  const theme = cleanTitleCandidate(settings.theme);
  const genre = cleanTitleCandidate(settings.genre);
  if (theme) return limitChars(`${theme}の物語`, MAX_TITLE_CHARS);
  if (genre) return limitChars(`${genre}の物語`, MAX_TITLE_CHARS);
  return '名称未設定の小説';
}

function dropTitleLine(body, title) {
  const lines = normalizeText(body).split('\n');
  const normalizedTitle = cleanTitleCandidate(title);
  if (!normalizedTitle || !lines.length) return body;
  return lines
    .filter((line, index) => {
      const trimmed = line.trim();
      const labeled = trimmed.match(TITLE_LABEL_LINE_PATTERN);
      if (labeled) {
        return cleanTitleCandidate(labeled[1]) !== normalizedTitle;
      }
      return !(index === 0 && cleanTitleCandidate(trimmed) === normalizedTitle);
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function stripChapterHeadingPrefix(value) {
  const line = compactSpaces(value);
  if (!line || isChapterHeadingLine(line)) return '';
  return line.replace(CHAPTER_HEADING_PREFIX_PATTERN, '').trim();
}

function cleanSubmissionBody(body) {
  return normalizeText(body)
    .split('\n')
    .filter(line => !TITLE_LABEL_LINE_PATTERN.test(line.trim()))
    .filter(line => !STANDALONE_FINISH_PATTERN.test(line.trim()))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function extractSubmissionBody(storyText, title) {
  const withoutFooter = stripStoryMakerFooter(storyText);
  return cleanSubmissionBody(dropTitleLine(withoutFooter, title));
}

function contentLines(text) {
  return normalizeText(text)
    .split('\n')
    .map(line => stripChapterHeadingPrefix(line))
    .filter(line => charLength(line) >= 8)
    .filter(line => !TITLE_LABEL_LINE_PATTERN.test(line));
}

function splitSentences(text) {
  const compact = compactSpaces(text);
  const matches = compact.match(/[^。！？!?]+[。！？!?]?/g) || [];
  return matches
    .map(sentence => sentence.trim())
    .filter(sentence => charLength(sentence) >= 8);
}

function buildIntroduction(body, title, settings = {}) {
  const summaryText = contentLines(body).join('\n');
  const sentences = splitSentences(summaryText);
  const lead = sentences.slice(0, 3).join('');
  if (lead) return limitChars(lead, MAX_INTRODUCTION_CHARS, '...');

  const theme = compactSpaces(settings.theme || '');
  const genre = compactSpaces(settings.genre || settings.modeLabel || '物語');
  const worldview = compactSpaces(settings.worldview || '');
  const axes = [worldview, theme].filter(Boolean).join('、');
  const frame = axes ? `${axes}を軸にした${genre}です。` : `${genre}として読める一作です。`;
  return limitChars(`『${title}』は、${frame}登場人物の選択と関係の変化を本文の温度感に沿って描きます。`, MAX_INTRODUCTION_CHARS, '...');
}

function normalizeTag(value) {
  return limitChars(
    compactSpaces(value)
      .replace(/^#+/, '')
      .replace(/[、。！？!?：:;；（）()\[\]{}「」『』【】]/g, '')
      .trim(),
    MAX_TAG_CHARS,
  );
}

function addTag(tags, value) {
  const tag = normalizeTag(value);
  if (tag && !tags.includes(tag)) tags.push(tag);
}

function mapGenre(value = '') {
  const source = String(value || '').toLowerCase();
  if (/恋愛|ラブコメ|romance/.test(source)) return { hotGenre: '恋愛', category: '恋愛' };
  if (/ファンタジ|fantasy|異世界|魔法|剣|竜|ドラゴン/.test(source)) return { hotGenre: 'ファンタジー', category: 'ファンタジー' };
  if (/sf|宇宙|未来|ai|ロボ|サイバ|タイム/.test(source)) return { hotGenre: 'SF', category: 'SF' };
  if (/ホラー|怪談|幽霊|呪|恐怖/.test(source)) return { hotGenre: 'ホラー', category: 'ホラー' };
  if (/ミステリ|推理|事件|探偵|サスペンス/.test(source)) return { hotGenre: 'ミステリー', category: 'ミステリー' };
  if (/歴史|時代|戦国|江戸|明治|大正|幕末/.test(source)) return { hotGenre: '歴史・時代', category: '歴史・時代' };
  if (/児童|童話|絵本|詩/.test(source)) return { hotGenre: '児童書・童話', category: '児童書・童話' };
  if (/エッセイ|随筆|ノンフィクション|実話/.test(source)) return { hotGenre: 'ライト文芸', category: 'エッセイ・ノンフィクション' };
  if (/キャラ文芸|現代|日常|青春|学園|家族|仕事/.test(source)) return { hotGenre: 'キャラ文芸', category: 'キャラ文芸' };
  return { hotGenre: 'ライト文芸', category: 'ライト文芸' };
}

function inferLengthKind(body, episodes) {
  const chars = charLength(body);
  if ((episodes?.length || 0) >= 3 || chars >= 10000) return '長編';
  if ((episodes?.length || 0) <= 1 && chars <= 2200) return 'ショートショート';
  return '短編';
}

function inferWritingStatus(body, episodes) {
  if (/【完】|完結|おわり|終わり/.test(body)) return '完結';
  if ((episodes?.length || 0) <= 1 && charLength(body) < 8000) return '完結';
  return '連載中';
}

function detectRating(body) {
  const ratings = [];
  if (/血|惨殺|拷問|遺体|死体|虐殺|切断|内臓|グロ|残酷|暴力|殺人|戦闘/.test(body)) {
    ratings.push('R15');
  }
  if (/性描写|性行為|官能|成人向け/.test(body)) {
    ratings.push('R18相当は要確認');
  }
  return ratings.length ? ratings.join(' / ') : 'なし';
}

function buildTags(settings = {}, mappedGenre) {
  const tags = [];
  addTag(tags, mappedGenre.category);
  addTag(tags, settings.theme);
  addTag(tags, settings.genre);
  addTag(tags, settings.worldview);
  addTag(tags, settings.target);
  addTag(tags, settings.ending);
  addTag(tags, settings.narration);
  return tags.slice(0, MAX_TAGS);
}

function buildDefaultEpisode(body, title) {
  return [{
    sectionName: '未設定',
    episodeTitle: limitChars(title || '第1話', MAX_TITLE_CHARS),
    body: normalizeText(body),
  }];
}

function splitAlphapolisEpisodes(body, title) {
  const lines = normalizeText(body).split('\n');
  const episodes = [];
  const preface = [];
  let current = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (isChapterHeadingLine(trimmed)) {
      if (current) episodes.push(current);
      const label = cleanHeadingLabel(trimmed) || `第${episodes.length + 1}章`;
      current = {
        sectionName: limitChars(label, MAX_TITLE_CHARS),
        episodeTitle: limitChars(label, MAX_TITLE_CHARS),
        lines: [],
      };
      preface.length = 0;
    } else if (current) {
      current.lines.push(line);
    } else if (trimmed) {
      preface.push(line);
    }
  }
  if (current) episodes.push(current);

  const mapped = episodes
    .map(episode => ({
      sectionName: episode.sectionName,
      episodeTitle: episode.episodeTitle,
      body: normalizeText(episode.lines.join('\n')),
    }))
    .filter(episode => charLength(episode.body) >= 40);

  if (preface.length && charLength(preface.join('\n')) >= 40) {
    mapped.unshift({
      sectionName: '未設定',
      episodeTitle: limitChars(title || '第1話', MAX_TITLE_CHARS),
      body: normalizeText(preface.join('\n')),
    });
  }

  return mapped.length ? mapped : buildDefaultEpisode(body, title);
}

export function buildAlphapolisPreview({ storyText = '', settings = {} } = {}) {
  const title = extractTitle(storyText, settings);
  const body = extractSubmissionBody(storyText, title);
  const mappedGenre = mapGenre([
    settings.genre,
    settings.theme,
    settings.worldview,
    settings.modeLabel,
    settings.target,
  ].filter(Boolean).join(' '));
  const episodes = splitAlphapolisEpisodes(body, title);
  const preview = {
    title,
    introduction: buildIntroduction(body, title, settings),
    hotGenre: mappedGenre.hotGenre,
    category: mappedGenre.category,
    lengthKind: inferLengthKind(body, episodes),
    writingStatus: inferWritingStatus(body, episodes),
    rating: detectRating(body),
    tags: buildTags(settings, mappedGenre),
    coverImage: '未設定',
    impressions: '有り',
    body,
    episodes,
  };
  preview.copyAll = formatAlphapolisPreview(preview);
  return preview;
}

export function formatAlphapolisPreview(preview) {
  const lines = [
    'アルファポリス作品情報',
    `タイトル: ${preview.title}`,
    `内容紹介:\n${preview.introduction}`,
    `HOTランキング用ジャンル: ${preview.hotGenre}`,
    `カテゴリ: ${preview.category}`,
    `長編・短編: ${preview.lengthKind}`,
    `執筆状態: ${preview.writingStatus}`,
    `R指定: ${preview.rating}`,
    `タグ:\n${preview.tags.join('\n')}`,
    `表紙画像: ${preview.coverImage}`,
    `感想の受付: ${preview.impressions}`,
    '章・話の貼り付け',
  ];
  preview.episodes.forEach((episode, index) => {
    lines.push([
      `# ${index + 1}`,
      `章の設定: ${episode.sectionName}`,
      `話タイトル: ${episode.episodeTitle}`,
      `本文:\n${episode.body}`,
    ].join('\n'));
  });
  return lines.join('\n\n');
}

function readActiveChipText(selector) {
  return document.querySelector(selector)?.textContent?.trim() || '';
}

function readInputValue(id) {
  return document.getElementById(id)?.value?.trim() || '';
}

function readAxisValue(axis) {
  return (
    readInputValue(`${axis}-custom`)
    || readActiveChipText(`#${axis}-sub-chips .chip.active`)
    || readActiveChipText(`#${axis}-cat-chips .chip.active`)
  );
}

function readSettingsFromDom() {
  return {
    modeLabel: readInputValue('mode-custom') || readActiveChipText('#mode-chips .chip.active'),
    theme: readAxisValue('theme'),
    genre: readAxisValue('genre'),
    worldview: readAxisValue('worldview'),
    target: readAxisValue('target'),
    era: readAxisValue('era'),
    ending: readAxisValue('ending'),
    narration: readAxisValue('narr'),
  };
}

function renderCopyButton(kind, options = {}) {
  const label = options.label || 'コピー';
  const title = options.title || `${label}します`;
  const index = options.index === undefined ? '' : ` data-copy-index="${Ce(String(options.index))}"`;
  const className = options.className ? ` ${options.className}` : '';
  return `<button type="button" class="btn-secondary kakuyomu-copy-btn alphapolis-copy-btn${className}" data-copy-kind="${Ce(kind)}"${index} title="${Ce(title)}" aria-label="${Ce(title)}">${Ce(label)}</button>`;
}

function renderRow({ label, value, kind, note = '', multiline = false, contentHtml = '', hideAction = false }) {
  const valueClass = multiline ? 'kakuyomu-preview-value is-multiline' : 'kakuyomu-preview-value';
  const body = contentHtml || `<div class="${valueClass}">${Ce(value)}</div>`;
  const noteHtml = note ? `<div class="kakuyomu-preview-note">${Ce(note)}</div>` : '';
  const actionHtml = hideAction ? '' : renderCopyButton(kind);
  return `
    <div class="kakuyomu-preview-row alphapolis-preview-row">
      <div class="kakuyomu-preview-label">${Ce(label)}</div>
      <div class="kakuyomu-preview-content">${body}${noteHtml}</div>
      <div class="kakuyomu-preview-actions">${actionHtml}</div>
    </div>
  `;
}

function renderTags(preview) {
  const tags = preview.tags.map(tag => `<span class="kakuyomu-tag">${Ce(tag)}</span>`).join('');
  return renderRow({
    label: 'タグ',
    kind: 'tags',
    note: '1タグ20文字以内、最大10個の貼り付け候補です。',
    contentHtml: `<div class="kakuyomu-tag-list">${tags}</div>`,
  });
}

function renderEpisode(episode, index) {
  return `
    <section class="kakuyomu-body-block alphapolis-episode-block">
      <div class="kakuyomu-body-block-head">
        <div>
          <div class="kakuyomu-body-block-title">#${index + 1} ${Ce(episode.episodeTitle)}</div>
          <div class="kakuyomu-body-block-meta">${charLength(episode.body)}字 / 章の設定: ${Ce(episode.sectionName)}</div>
        </div>
        <div class="kakuyomu-body-block-actions">
          ${renderCopyButton('sectionName', { label: '章名コピー', index })}
          ${renderCopyButton('episodeTitle', { label: '話タイトルコピー', index })}
          ${renderCopyButton('episodeBody', { label: '本文コピー', index, className: 'kakuyomu-chapter-copy' })}
        </div>
      </div>
      <pre class="kakuyomu-body-preview kakuyomu-chapter-preview">${Ce(episode.body)}</pre>
    </section>
  `;
}

function renderEpisodes(preview) {
  return `<div class="kakuyomu-body-sections alphapolis-episode-list">${preview.episodes.map((episode, index) => renderEpisode(episode, index)).join('')}</div>`;
}

export function renderAlphapolisPreview(preview) {
  return `
    <div class="kakuyomu-preview-titlebar alphapolis-preview-titlebar">
      <div>
        <div class="kakuyomu-preview-kicker">Alphapolis Form Preview</div>
        <div class="kakuyomu-preview-name">${Ce(preview.title)}</div>
      </div>
      <span class="kakuyomu-preview-count">${charLength(preview.title)} / ${MAX_TITLE_CHARS}字</span>
    </div>
    ${renderRow({ label: 'タイトル', value: preview.title, kind: 'title', note: '70文字以内' })}
    ${renderRow({ label: '内容紹介', value: preview.introduction, kind: 'introduction', multiline: true, note: '1,200文字以内' })}
    ${renderRow({ label: 'HOTランキング用ジャンル', value: preview.hotGenre, kind: 'hotGenre' })}
    ${renderRow({ label: 'カテゴリ', value: preview.category, kind: 'category' })}
    ${renderRow({ label: '長編・短編', value: preview.lengthKind, kind: 'lengthKind' })}
    ${renderRow({ label: '執筆状態', value: preview.writingStatus, kind: 'writingStatus' })}
    ${renderRow({ label: 'R指定', value: preview.rating, kind: 'rating' })}
    ${renderTags(preview)}
    ${renderRow({ label: '表紙画像', value: preview.coverImage, kind: 'coverImage' })}
    ${renderRow({ label: '感想の受付', value: preview.impressions, kind: 'impressions' })}
    ${renderRow({ label: '章・話', kind: 'episodeBody', multiline: true, hideAction: true, contentHtml: renderEpisodes(preview) })}
  `;
}

export function getAlphapolisCopyValue(preview, kind, options = {}) {
  const index = Number(options.episodeIndex ?? options.tagIndex);
  if (kind === 'sectionName') return Number.isInteger(index) ? preview.episodes?.[index]?.sectionName || '' : '';
  if (kind === 'episodeTitle') return Number.isInteger(index) ? preview.episodes?.[index]?.episodeTitle || '' : '';
  if (kind === 'episodeBody') return Number.isInteger(index) ? preview.episodes?.[index]?.body || '' : '';
  const values = {
    all: preview.copyAll,
    title: preview.title,
    introduction: preview.introduction,
    hotGenre: preview.hotGenre,
    category: preview.category,
    lengthKind: preview.lengthKind,
    writingStatus: preview.writingStatus,
    rating: preview.rating,
    tags: preview.tags.join('\n'),
    coverImage: preview.coverImage,
    impressions: preview.impressions,
    body: preview.body,
  };
  return values[kind] || '';
}

function restoreButtonText(button, originalText) {
  setTimeout(() => {
    button.textContent = originalText;
    button.classList.remove('is-copied');
  }, 1200);
}

async function copyText(value, button) {
  const text = String(value || '');
  if (!text) return;
  const originalText = button.textContent;
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.setAttribute('readonly', '');
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    textarea.remove();
  }
  button.textContent = 'コピー済み';
  button.classList.add('is-copied');
  restoreButtonText(button, originalText);
}

function saveTextFile(value, button) {
  const text = String(value || '');
  if (!text) return;
  const originalText = button.textContent;
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = buildStoryExportFileName('AlphapolisForm', 'txt');
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  button.textContent = '保存済み';
  button.classList.add('is-copied');
  restoreButtonText(button, originalText);
}

function outputHasStory(outputEl) {
  if (!outputEl || outputEl.classList.contains('empty')) return false;
  return charLength(stripStoryMakerFooter(outputEl.innerText || outputEl.textContent || '')) >= 40;
}

function isStoryGenerationActive() {
  const settingsEl = document.getElementById('settings');
  const generateButton = document.getElementById('btn-generate');
  return Boolean(settingsEl?.classList.contains('generating') || generateButton?.disabled);
}

export function installAlphapolisAssist() {
  const outputEl = document.getElementById('output');
  const rootEl = document.getElementById('alphapolis-assist');
  const checkbox = document.getElementById('alphapolis-assist-enable');
  const bodyEl = document.getElementById('alphapolis-assist-body');
  const previewEl = document.getElementById('alphapolis-form-preview');
  const statusEl = document.getElementById('alphapolis-assist-status');
  if (!outputEl || !rootEl || !checkbox || !bodyEl || !previewEl || !statusEl) return;

  let lastPreview = null;
  let queued = false;
  let busy = false;

  const setCopyControlsDisabled = disabled => {
    bodyEl.querySelectorAll('.alphapolis-copy-btn, .alphapolis-save-btn').forEach(button => {
      button.disabled = Boolean(disabled);
    });
  };

  const applyLockedUi = (value, message = '処理完了後に最新内容へ更新') => {
    const locked = Boolean(value);
    rootEl.classList.toggle('is-busy', locked);
    rootEl.setAttribute('aria-busy', locked ? 'true' : 'false');
    checkbox.disabled = locked || !outputHasStory(outputEl);
    setCopyControlsDisabled(locked);
    if (locked) statusEl.textContent = message;
  };

  const setBusy = value => {
    busy = Boolean(value);
    applyLockedUi(busy);
  };

  const refresh = () => {
    queued = false;
    const generationActive = isStoryGenerationActive();
    if (busy || generationActive) {
      applyLockedUi(true, generationActive ? '生成完了後に最新内容へ更新' : '処理完了後に最新内容へ更新');
      return;
    }
    applyLockedUi(false);
    const enabled = checkbox.checked;
    const canPreview = outputHasStory(outputEl);
    checkbox.disabled = !canPreview;
    bodyEl.classList.toggle('hidden', !enabled || !canPreview);
    if (!canPreview) {
      lastPreview = null;
      statusEl.textContent = '出力後に表示';
      previewEl.innerHTML = '';
      setCopyControlsDisabled(true);
      return;
    }
    const storyText = outputEl.innerText || outputEl.textContent || '';
    lastPreview = buildAlphapolisPreview({
      storyText,
      settings: readSettingsFromDom(),
    });
    statusEl.textContent = enabled
      ? `表示中: ${lastPreview.episodes.length}話 / ${lastPreview.tags.length}タグ候補`
      : 'チェックで表示';
    if (enabled) previewEl.innerHTML = renderAlphapolisPreview(lastPreview);
    setCopyControlsDisabled(!enabled);
  };

  const scheduleRefresh = () => {
    if (queued) return;
    queued = true;
    window.requestAnimationFrame(refresh);
  };

  checkbox.checked = false;
  checkbox.addEventListener('change', refresh);
  window.addEventListener('story-maker:alphapolis-busy', event => {
    setBusy(event.detail?.busy);
    if (!busy) scheduleRefresh();
  });
  window.addEventListener('story-maker:alphapolis-refresh', scheduleRefresh);

  bodyEl.addEventListener('click', event => {
    const saveButton = event.target?.closest?.('.alphapolis-save-btn');
    if (saveButton && !saveButton.disabled && !busy && lastPreview) {
      saveTextFile(lastPreview.copyAll, saveButton);
      return;
    }
    const button = event.target?.closest?.('.alphapolis-copy-btn');
    if (!button || button.disabled || busy || !lastPreview) return;
    copyText(getAlphapolisCopyValue(lastPreview, button.dataset.copyKind, {
      episodeIndex: button.dataset.copyIndex,
      tagIndex: button.dataset.copyIndex,
    }), button);
  });

  ['mode', 'theme', 'genre', 'worldview', 'target', 'era', 'ending', 'narr'].forEach(axis => {
    document.getElementById(`${axis}-custom`)?.addEventListener('input', scheduleRefresh);
    document.getElementById(`${axis}-custom`)?.addEventListener('change', scheduleRefresh);
  });
  document.addEventListener('click', event => {
    if (event.target?.closest?.('.chip, .btn-all-random, #btn-rand-mode')) {
      setTimeout(scheduleRefresh, 0);
    }
  });

  const observer = new MutationObserver(scheduleRefresh);
  observer.observe(outputEl, {
    childList: true,
    characterData: true,
    subtree: true,
    attributes: true,
    attributeFilter: ['class'],
  });
  const settingsEl = document.getElementById('settings');
  const generateButton = document.getElementById('btn-generate');
  if (settingsEl) {
    observer.observe(settingsEl, {
      attributes: true,
      attributeFilter: ['class'],
    });
  }
  if (generateButton) {
    observer.observe(generateButton, {
      childList: true,
      characterData: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['disabled', 'class'],
    });
  }
  refresh();
}
