// Story Maker v4.9.9 public output cleanup.
// This is intentionally small and mode-scoped; it removes app/prompt artifacts, not story content.

import {
  PUBLIC_MODE_VALUES,
  detectModeFromText,
} from './modeContracts.js';

function currentMode() {
  const active = document.querySelector('#mode-chips button.active');
  const activeValue = active?.dataset?.v || '';
  if (PUBLIC_MODE_VALUES.includes(activeValue)) return activeValue;
  return detectModeFromText([
    active?.textContent,
    document.getElementById('mode-custom')?.value,
  ].filter(Boolean).join(' '));
}

function stripInternalLead(text) {
  let next = String(text || '');
  next = next.replace(/^【[^】]{0,80}(?:本文|配置|接続詞|リズム|注意)[^】]{0,80}】\s*/u, '');
  next = next.replace(/^(?:余計な接続詞|リズムに緩急|人間臭さを出すため|タイトルは禁止|本文は)[^\n]{0,160}\n+/u, '');
  return next;
}

function cleanEssay(text) {
  let next = stripInternalLead(text);
  const firstBlock = next.search(/主張:/);
  if (firstBlock > 0 && firstBlock < 220) {
    next = next.slice(firstBlock);
  }
  next = next.replace(/^タイトル:[^\n]*(?=主張:)/u, '');
  next = next.replace(/\n?【完】\s*(?=\n|$)/g, '');
  next = next.replace(/\n?完結\s*(?=\n|$)/g, '');
  return next;
}

function cleanGenericPublicMode(text) {
  return stripInternalLead(String(text || '')).replace(/\n{3,}/g, '\n\n');
}

export function cleanOutputForPublicMode(text, mode = currentMode()) {
  if (!PUBLIC_MODE_VALUES.includes(mode)) return String(text || '');
  if (mode === 'essay') return cleanEssay(text);
  if (['poem', 'letter', 'diary', 'documentary', 'radio'].includes(mode)) {
    return cleanGenericPublicMode(text).replace(/\n?【完】\s*(?=\n|$)/g, '');
  }
  return cleanGenericPublicMode(text);
}

export function installPublicOutputCleanup() {
  const output = document.getElementById('output');
  if (!output) return;

  let applying = false;
  const apply = () => {
    if (applying) return;
    const mode = currentMode();
    if (!PUBLIC_MODE_VALUES.includes(mode)) return;
    const text = output.innerText || output.textContent || '';
    if (!text || !/Generated By AI Story Maker|【完】|接続詞|本文を続けて|タイトル:/u.test(text)) return;
    const cleaned = cleanOutputForPublicMode(text, mode);
    if (cleaned === text) return;
    applying = true;
    output.textContent = cleaned;
    applying = false;
  };

  new MutationObserver(apply).observe(output, {
    childList: true,
    characterData: true,
    subtree: true,
  });
  setInterval(apply, 1000);
}
